######################################################################
# LuckyChat 配置文件
# 此份文件为Spigot端的LuckyChat插件配置文件，
# 该插件用于实现Minecraft服务端内消息与QQ群消息互相广播，
# 即当玩家在Minecraft游戏中发送消息时，bot会向群内发送该消息，反之亦然。
# 注：bot即为QQ机器人
######################################################################
# 以下是对该插件运行机制的解释，建议在修改配置文件前先了解：
# 本次插件可以实现“会话互相独立，会话内多群多服互通”功能。
#
# 首先，bot程序和MC服务端的关系为服务端和客户端的关系，它们可以说是一套配套的插件。
# bot程序启动后加载bot端插件，开始监听某一端口（默认54100）。
#
# bot端插件以会话（Session）为单位，每个会话保存了会话名、会话号和群列表，
# 这三项是由bot端决定的（详细情况请了解bot端插件，此处仅对使用进行解释），
# 如果群列表中的某个群中出现了消息，该条消息会被bot同步转发到群列表的其他群中，
# 即“群群互通”。
#
# 当MC端（即本插件）携带指定的会话号连接bot端的连接地址时，bot端会将该连接
# “添加”到会话中，此时在同一个会话中的群列表和连接的MC端消息互通，即“群服互通”。
# 这里需要注意的是，bot端无法预测连入的MC端的来源，仅仅只是做了有连接时将连接
# 交给会话处理的工作，因此，下方的配置文件为需要提交给bot端的一些信息。
#
# 当有多个MC端携带相同的会话号连接同一个bot端时，该会话就维护了两个MC端连接，
# 此时两个MC端的消息也是互通的，即实现“服服互通”。
#
# 以下列举多个例子以辅助理解：
# 例子1：
#     会话1 群列表：群123，群456，群789
#     会话1 MC连接列表：无
#     此时若群123有人发送消息，则群456和群789都能收到该消息
# 例子2：
#     会话1 群列表：群123，群456
#     会话1 MC连接列表：MC服1 MC服2
#     此时若群123有人发送消息，则群456、MC服1、MC服2都能收到该消息
#     若MC服1有人发送消息，则群123、群456、MC服2都能收到消息
# 例子3：
#     会话1 群列表：群123
#     会话1 MC连接列表：MC服1
#     会话2 群列表：群456
#     会话2 MC连接列表：MC服2
#     此时群123和MC服1消息互通，群456和MC服2消息互通，而群123和群456、MC服2消息不互通
#     即：会话是独立的，不同的会话互不影响
#
# 综上，可以通俗解释为：同一会话中的群和MC端连接消息互通，不同会话互不影响。
######################################################################
# 由于bot端无法预测连入的MC端，且为了使得消息格式自定义程度更高，
# 我们将消息格式的定义权交给了MC端，而以下的format里的内容则为消息的格式，
# 定义的格式是一个字符串，并用占位符代替实际显示内容，当实际内容到来时，
# 这些占位符会被替换成实际的内容。
######################################################################

# bot中定义了一些与bot端插件相关的配置
bot:
  # 连接bot端的地址和端口
  host: "localhost"
  port: 54100
  
  # 连接失败尝试重连时间
  # 当连接失败时经过几秒后重新尝试连接
  retryTimes: 5

  # 会话号
  # 若提供的会话号不存在，则拒绝连接，并要求使用/mcchat reload指令重新开启连接尝试
  sessionId: 12345

# 服务器名字
# 在下方的消息格式定义中可以使用占位符%serverName%来获得服务器名字
serverName: "MinecraftServer"

# 消息格式
# 各项注释请不要删除，方便随时查阅
format:
  ######################################################################
  # 该条消息格式是来自于QQ群消息的消息格式，将被发送到MC游戏中
  # 以下为所有占位符，在实际运行过程中这些占位符会被实际数据替代：
  # %sessionName%    会话备注（由bot端决定）
  # %groupId%    群号
  # %groupName%    群名
  # %groupNickname%    群昵称（由bot端决定，相当于给群起的别名）
  # %senderId%    发送者qq
  # %senderNickname%    发送者昵称
  # %senderGroupNickname%    发送者的群昵称（若无，则此占位符会被自动填充发送者昵称）
  # %message%    消息内容
  fromBot: "[%groupNickname%] <%senderGroupNickname%> %message%"
  ######################################################################

  ######################################################################
  # 以下的消息格式均为发送到qq群消息的消息格式，将被发送到QQ群和其它在同一个会话的MC端中
  # 接下来的每一项内容的占位符未必相同

  # 该消息为当玩家进入游戏时发送
  # %playerName%    加入游戏玩家的ID
  join: "[%serverName%] %playerName% 加入了游戏"

  # 该消息为当玩家离开游戏时发送
  # %playerName%    离开游戏玩家的ID
  quit: "[%serverName%] %playerName% 离开了游戏"

  # 该消息为当玩家发送消息时发送
  # %playerName%    发送消息的玩家ID
  # %message%    消息内容
  message: "[%serverName%] %playerName% 说 %message%"

  # 该消息为当玩家死亡时发送
  # %playerName%    死亡的玩家ID
  # %deathMessage%    死亡信息（此信息已经包含玩家ID，相当于游戏里聊天框显示的死亡信息）
  death: "[%serverName%] %deathMessage%"

  # 该消息为当玩家被踢出时发送
  # %playerName%    被踢的玩家ID
  # %kickReason%    踢出原因
  kick: "[%serverName%] %playerName% 被踢了，因为 %kickReason%"
  ######################################################################