name: LuckyMinecraftQQChatSpigot
version: 1.2
main: fun.boomcat.luckyhe.spigot.plugin.luckyminecraftqqchatspigot.LuckyMinecraftQQChatSpigot
commands:
  mcchat:
    description: 与控制MC和BOT之间的连接相关
    usage: /mcchat

  qq:
    description: 与绑定QQ相关
    usage: /qq