name: LuckyMinecraftQQChatSpigot
version: 1.1
main: fun.boomcat.luckyhe.spigot.plugin.luckyminecraftqqchatspigot.LuckyMinecraftQQChatSpigot
commands:
  mcchat:
    description: 与控制MC和BOT之间的连接相关
    usage: /mcchat